version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    # Optional but recommended configurations
    labels:
      - "dependencies"
      - "python"
      - "pipenv"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    # Optional: Add reviewers or assignees
    reviewers:
      - "TheMat556"
